### ISSUE TITLE
Add tests for recurrence coefficients

### ISSUE THREAD

**Issue by timueh** [timueh/PolyChaos.jl#4]
We need to test the functions inside [`recurrence_coefficients_monic.jl`](https://github.com/timueh/PolyChaos.jl/blob/master/src/recurrence_coefficients_monic.jl).

We should take the functions from the OPQ suite as a reference.

**Comment by FrederikZa** [comment]
Tests are up and passing.

**Comment by timueh** [comment]
closed with [e1de2d7](https://github.com/timueh/PolyChaos.jl/commit/e1de2d7257faec53892a44c07b19093ebd2b32c4)
