### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [timueh/PolyChaos.jl#47]
This is causing some downstream compat issues that seem fixed on master.

**Comment by timueh** [comment]
I'm not quite sure I understand the problem?!.. What am I missing? Happy to help!

**Comment by ChrisRackauckas** [comment]
The last tag is from awhile ago so it would be good if current master could get a tag.

**Comment by timueh** [comment]
ahhh! I see.

**Comment by vavrines** [comment]
Adding a tag manually is feasible, but a minor update of release version could also be done.
I guess we have something new like the support of uniform distribution [-1,1] and the fix of compatibility issue : )

**Comment by ChrisRackauckas** [comment]
I just meant register a new version. @JuliaRegistrator register(). Copy paste that and 👍

**Comment by timueh** [comment]
Sorry, my bad @ChrisRackauckas. I relocated, started a new job, and what not. ;)

**Comment by timueh** [comment]
@JuliaRegistrator register()

**Comment by timueh** [comment]
@JuliaTagBot register()

**Comment by timueh** [comment]
@JuliaTagBot register()

**Comment by timueh** [comment]
Mh.. why is the TagBot action skipped?..

**Comment by vavrines** [comment]
I guess you need to update TagBot yml.
https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249

**Comment by timueh** [comment]
I believe the `TagBot.yml` is correct.. @ChrisRackauckas, do you have an idea?

**Comment by ChrisRackauckas** [comment]
The issue is that @JuliaRegistrator register() failed because you needed to increment the tag.

Also, you need to have the compats for this to work.

Do you want some help maintaining this? I'd be willing to clean that all up.

**Comment by timueh** [comment]
Hi @ChrisRackauckas, I'd greatly appreciate your help! I see that you opened a PR already.

**Comment by ChrisRackauckas** [comment]
Awesome.

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
