### ISSUE TITLE
Add tests for quadrature rules

### ISSUE THREAD

**Issue by timueh** [timueh/PolyChaos.jl#5]
We need to validate the quadature rules from [`quadrature_rules.jl`](https://github.com/timueh/PolyChaos.jl/blob/master/src/quadrature_rules.jl).

**Comment by timueh** [comment]
I improved the performance of most of the quadrature rules, see commit [`b5c80a9`](https://github.com/timueh/PolyChaos.jl/commit/b5c80a95ee6ea0ea79cf4a2f3f8231cc0480ab4e).

**Comment by FrederikZa** [comment]
Tests for most of the functions are added in commit ca7dd66a2e1c7a01ccbb640ed4f0205703c48a48 .
