### ISSUE TITLE
Error on Uniform01Measure

### ISSUE THREAD

**Issue by Alexander-Murray** [timueh/PolyChaos.jl#50]
I tried to use the following command following the [Numerical Integration tutorial](https://timueh.github.io/PolyChaos.jl/stable/numerical_integration/):
`Uniform01Measure(PolyChaos.w_uniform01, (0.0, 1.0), true)`
However I get the following error message:
```
MethodError: no method matching Uniform01Measure(::typeof(w_uniform01), ::Tuple{Float64,Float64}, ::Bool)

Stacktrace:
 [1] top-level scope at In[7]:1
 [2] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091
```

**Comment by timueh** [comment]
Hey Alex,

I'm not sure, I can follow. I get the following

```julia
julia> using PolyChaos
julia> measure = Uniform01Measure()
Uniform01Measure(PolyChaos.w_uniform01, (0.0, 1.0), true)
```

This is exactly the output to be expected?

Are you using `v0.2.3`?

**Comment by Alexander-Murray** [comment]
Yes, I am using v0.2.3. I think the error lies in the syntax since calling `Uniform01Measure()` works without issue. However, to integrate from -1 to 1 I tried using `Uniform01Measure(PolyChaos.w_uniform01, (-1.0, 1.0), true)` given the form of the output when no argument is given to Uniform01Measure. What would be the correct syntax in this case?

**Comment by timueh** [comment]
Did you see [this issue](https://github.com/timueh/PolyChaos.jl/issues/30)?

Does using `Uniform_11Measure` and `Uniform_11Orthopoly` do the job?

**Comment by Alexander-Murray** [comment]
No, I didn't see that issue. That does solve the problem though!
